// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ysZ8nuaOr6tcxlckqVjo82e_dJOqe_8',
    appId: '1:592426659484:web:65b8ccc00e8a6e7721c759',
    messagingSenderId: '592426659484',
    projectId: 'farmfederate-advisor',
    authDomain: 'farmfederate-advisor.firebaseapp.com',
    storageBucket: 'farmfederate-advisor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ysZ8nuaOr6tcxlckqVjo82e_dJOqe_8',
    appId: '1:592426659484:android:65b8ccc00e8a6e7721c759',
    messagingSenderId: '592426659484',
    projectId: 'farmfederate-advisor',
    authDomain: 'farmfederate-advisor.firebaseapp.com',
    storageBucket: 'farmfederate-advisor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ysZ8nuaOr6tcxlckqVjo82e_dJOqe_8',
    appId: '1:592426659484:ios:65b8ccc00e8a6e7721c759',
    messagingSenderId: '592426659484',
    projectId: 'farmfederate-advisor',
    authDomain: 'farmfederate-advisor.firebaseapp.com',
    storageBucket: 'farmfederate-advisor.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ysZ8nuaOr6tcxlckqVjo82e_dJOqe_8',
    appId: '1:592426659484:macos:65b8ccc00e8a6e7721c759',
    messagingSenderId: '592426659484',
    projectId: 'farmfederate-advisor',
    authDomain: 'farmfederate-advisor.firebaseapp.com',
    storageBucket: 'farmfederate-advisor.firebasestorage.app',
  );
}
